# Generated by Django 6.1 on 2026-08-24 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_id', models.CharField(max_length=50)),
                ('verified_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('verified_by_user_agent', models.CharField(blank=True, max_length=500)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField()),
            ],
            options={
                'verbose_name': 'verification log',
                'verbose_name_plural': 'verification logs',
                'ordering': ['-verified_at'],
            },
        ),
    ]
