# Generated by Django 6.1 on 2026-10-01 21:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('path', models.CharField(default='/', max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'site visit',
                'verbose_name_plural': 'site visits',
                'ordering': ['-visited_at'],
            },
        ),
    ]
