# Generated by Django 6.1 on 2026-09-02 11:41

import certificate_templates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='accent_color',
            field=models.CharField(blank=True, default='#e2d19f', max_length=50),
        ),
        migrations.AddField(
            model_name='template',
            name='badge_text',
            field=models.CharField(blank=True, default='VERIFIED CREDENTIAL', max_length=100),
        ),
        migrations.AddField(
            model_name='template',
            name='presentation_line',
            field=models.CharField(blank=True, default='This is proudly presented to', max_length=255),
        ),
        migrations.AddField(
            model_name='template',
            name='primary_color',
            field=models.CharField(blank=True, default='#0f2744', max_length=50),
        ),
        migrations.AddField(
            model_name='template',
            name='purpose',
            field=models.CharField(blank=True, default='General Recognition', max_length=255),
        ),
        migrations.AddField(
            model_name='template',
            name='secondary_color',
            field=models.CharField(blank=True, default='#c59b27', max_length=50),
        ),
        migrations.AddField(
            model_name='template',
            name='subtitle',
            field=models.CharField(blank=True, default='ACHIEVEMENT', max_length=100),
        ),
        migrations.AddField(
            model_name='template',
            name='title_prefix',
            field=models.CharField(blank=True, default='CERTIFICATE OF', max_length=100),
        ),
        migrations.AddField(
            model_name='template',
            name='wording_pattern',
            field=models.TextField(blank=True, default='for outstanding achievement and dedication in {{EVENT_NAME}}'),
        ),
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=certificate_templates.models.template_upload_path),
        ),
    ]
