# Generated by Django 6.1 on 2026-09-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate_templates', '0002_template_accent_color_template_badge_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='access_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='template',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
