# Generated by Django 6.1 on 2026-09-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificate_revocation_reason_certificate_revoked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='achievement',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='certificate',
            name='organization_name',
            field=models.CharField(blank=True, default='CertiGen Platform', max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signatory_name',
            field=models.CharField(blank=True, default='Authorized Signatory', max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signatory_title',
            field=models.CharField(blank=True, default='Program Director', max_length=255),
        ),
    ]
